### ISSUE TITLE
TOHE compatibility 

### ISSUE THREAD

**Issue by CoolModder** [Rabek009/MoreGamemodes#11]
I think TOHE would work well with this, and this is a smaller mod anyway. Compatibility could bring more players to the mod, and would overall be a big improvement.

**Comment by Rabek009** [comment]
I understand that people like both mods, but MG and TOHE aren't combinable mods. There are few mods that can be combined like crowded mod, submergen, better crewlink. But most of the mods aren't. To make MG compatible with TOHE would require entire mod rework and maybe even removing some gamemodes. Compatibility would cause many bugs too. And not all gamemodes can have roles. So it's better to keep it uncompatible. You can still join modded lobby with MG.
