### ISSUE TITLE
Can i port the proximity chat for tohe?

### ISSUE THREAD

**Issue by PHGaming121** [Rabek009/MoreGamemodes#15]
Well, i tried porting the proximity chat from this mod to tohe, but i didnt suceed.

Is there any way that i can do this?

**Comment by Rabek009** [comment]
Yes, you have to replace Main.ProximityMessages[pc.PlayerId].Add((toSend, 0f)); in SendProximityMessage() with pc.Notify(toSend, 3f + (toSend.Length / 10f));
