### ISSUE TITLE
public lobby 

### ISSUE THREAD

**Issue by jiggusuperking** [Rabek009/MoreGamemodes#18]
pls add public lobby support
because i need to play with who playing among us without mod players
pls add un modded players on find game he can see name show like this : {player name} mg 
[if host vanilla gamemode is changed to modded gamemode name show like this : {player name} [gamemode name]
 {unmodded players change to any vanilla gamemode it should show lobby}]
or not adding this i hate the mod

**Comment by artm04** [comment]
It's up to Innersloth unfortunately. Modded lobbies are private by default

**Comment by jiggusuperking** [comment]
what

**Comment by jiggusuperking** [comment]
why

**Comment by jiggusuperking** [comment]
is this modded handshake

**Comment by jiggusuperking** [comment]
nope this is a bug

**Comment by jiggusuperking** [comment]
you are making bug mod

**Comment by jiggusuperking** [comment]
you are definitely adding bugs to mod
you cant add public 
i hate mod like this
if has no public lobby support

**Comment by jiggusuperking** [comment]
you means garbage mod
